<a href="https://colab.research.google.com/github/mishra-amit-300266/ML-Engineer-Roadmap/blob/main/Week1_Python_Math_Pandas/_2_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Task 1: Array Creation
Create:
A 1D array of first 10 natural numbers
A 2D array of shape (3, 3) with random integers between 1-20
An identity matrix of size 4x4

In [2]:
arr1 = np.arange(1,11,1)
arr2 = np.random.randint(1,20,(3,3))
arr3 = np.eye(3)

Task 2: Indexing & Slicing
Given a 5x5 matrix of numbers from 1 to 25:
Extract the center 3x3 submatrix
Extract the diagonal elements
Print the last row and first column

In [4]:
arr4 = np.arange(1,26,1)
arr5 = np.reshape(arr4,(5,5))
print("Center 3x3 matrix:", arr5[1:4,1:4])
print("Diagonal elements:", arr5[0,0],arr5[1,1],arr5[2,2],arr5[3,3],arr5[4,4])
print("Sum of diagonal elements:", np.trace(arr5))
print("Last Row: ",arr5[4,:])
print("Last Column",arr5[:,4])

Center 3x3 matrix: [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Diagonal elements: 1 7 13 19 25
Sum of diagonal elements: 65
Last Row:  [21 22 23 24 25]
Last Column [ 5 10 15 20 25]


Task 3: Arithmetic Operations
Create two arrays: [1, 2, 3] and [4, 5, 6]

Perform element-wise addition, subtraction, and multiplication

Calculate their dot product

In [5]:
arr6 = np.array([1,2,3])
arr7 = np.array([4,5,6])
print(arr6+arr7)
print(arr6-arr7)
print(arr6*arr7)
print(np.dot(arr6,arr7))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
32


Task 4: Statistical Operations
Generate a 6x6 matrix of random floats between 0 and 1

Find its mean, max, min, standard deviation

Normalize it using min-max scaling

In [8]:
mat = np.random.rand(6,6)
print(np.mean(mat))
print(np.max(mat))
print(np.min(mat))
print(np.std(mat))
print("Normalize using min-max Scaling:", (mat-np.min(mat))/(np.max(mat)-np.min(mat)))

0.5431294124875836
0.9965521065212044
0.0074171734603502015
0.32367083677438446
Normalize using min-max Scaling: [[0.36054554 0.63421535 1.         0.11175749 0.92259456 0.75505436]
 [0.79167386 0.98649489 0.66997488 0.27049565 0.28041693 0.58186705]
 [0.46900765 0.217212   0.74473882 0.9408944  0.28480297 0.00949262]
 [0.93488762 0.94925021 0.         0.31599778 0.89870715 0.32445263]
 [0.91346644 0.07303034 0.43595881 0.61319543 0.41197777 0.11793298]
 [0.90170572 0.99028323 0.62073036 0.10411909 0.7332737  0.12727379]]


Task5:
Create a 3x3 matrix of all 2's
Multiply each row with [1,2,3] using broadcasting

In [9]:
arr7 = np.array([1,2,3])
arr8 = np.full((3,3),2)
print(arr8*arr7)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


 Task 6: Reshape & Stack
Create a 1D array of 16 numbers

Reshape it into 4x4

Split into two 2x4 matrices (horizontally)

Stack them vertically again



In [12]:
arr9 = np.arange(16)
arr10 = np.reshape(arr9,(4,4))
arr11 = arr10[:2,:]
arr12 = arr10[2:,:]
print(np.vstack((arr11,arr12)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Bonus Task: Build a NumPy-based Calculator
Create functions for:

Element-wise addition

Dot product

Matrix inversion

Transpose

In [14]:
def array_addition(arr1,arr2):
  print("Element wise addition:", arr1+arr2)
def array_dotProduct(arr1,arr2):
  print("Dot Product:", np.dot(arr1,arr2))
def array_inversion(arr1):
  try:
    print("Matrix Inversion:\n", np.linalg.inv(arr1))
  except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")
def array_transpose(arr1):
  print("Transpose:", arr1.T)

arr13 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr14 = np.array([[9,8,7],[6,5,4],[3,2,1]])
array_addition(arr13,arr14)
array_dotProduct(arr13,arr14)
array_inversion(arr13)
array_transpose(arr13)

Element wise addition: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Dot Product: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Matrix is singular and cannot be inverted.
Transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]
