<a href="https://colab.research.google.com/github/mishra-amit-300266/ML-Engineer-Roadmap/blob/main/Week1_Python_Math_Pandas/_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# NumPy Learning Notebook: Core Concepts & Uses

import numpy as np

In [2]:
# 1. Array Creation
arr1 = np.array([1, 2, 3])            # 1D array
arr2 = np.array([[1, 2], [3, 4]])     # 2D array
arr3 = np.zeros((2, 3))              # 2x3 array of zeros
arr4 = np.ones((3, 2))               # 3x2 array of ones
arr5 = np.eye(3)                     # Identity matrix
arr6 = np.arange(0, 10, 2)           # [0, 2, 4, 6, 8]
arr7 = np.linspace(0, 1, 5)          # 5 values from 0 to 1

In [3]:
print(arr1,arr2,arr3,arr4,arr5,arr6,arr7)

[1 2 3] [[1 2]
 [3 4]] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]
 [1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


In [4]:
# 2. Array Properties
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)
print("Dimensions:", arr2.ndim)

Shape: (2, 2)
Size: 4
Data type: int64
Dimensions: 2


In [5]:
# 3. Indexing & Slicing
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Element at row 1, col 2:", arr[1, 2])
print("First row:", arr[0])
print("First column:", arr[:, 0])
print("Submatrix:", arr[0:2, 1:3])

Element at row 1, col 2: 60
First row: [10 20 30]
First column: [10 40]
Submatrix: [[20 30]
 [50 60]]


In [6]:
# 4. Arithmetic Operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Addition:", x + y)
print("Multiplication:", x * y)
print("Dot product:", np.dot(x, y))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot product: 32


In [7]:
# 5. Useful Functions
mat = np.array([[1, 2], [3, 4]])
print("Sum:", np.sum(mat))
print("Mean:", np.mean(mat))
print("Standard Deviation:", np.std(mat))
print("Transpose:\n", mat.T)

Sum: 10
Mean: 2.5
Standard Deviation: 1.118033988749895
Transpose:
 [[1 3]
 [2 4]]


In [8]:
# 6. Reshaping & Flattening
original = np.arange(12)
reshaped = original.reshape((3, 4))
flattened = reshaped.flatten()
print("Original:", original)
print("Reshaped:", reshaped)
print("Flattened:", flattened)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
# 7. Stacking Arrays
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6]])
print("Vertical Stack:\n", np.vstack((arr_a, arr_b)))
print("Horizontal Stack:\n", np.hstack((arr_a, arr_a)))

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]
Horizontal Stack:
 [[1 2 1 2]
 [3 4 3 4]]


In [13]:
# 8. Random Number Generation
rand_arr = np.random.rand(2, 3)        # Uniform distribution
rand_ints = np.random.randint(0, 10, (2, 2))
normal_vals = np.random.randn(3, 3)    # Standard normal distribution
print("Random Array:\n", rand_arr)
print("Random Integers:\n", rand_ints)
print("Normal Values:\n", normal_vals)

Random Array:
 [[0.52016317 0.17167164 0.43171163]
 [0.30053392 0.96976357 0.11346015]]
Random Integers:
 [[6 2]
 [0 9]]
Normal Values:
 [[ 0.77263776 -0.31488056 -0.42078091]
 [ 1.16476762  0.19107746  0.40870479]
 [-0.45523557  0.26439173 -0.64745747]]


In [14]:
# 9. Logical Operations
logical_arr = np.array([10, 20, 30, 40])
print("Elements > 25:", logical_arr[logical_arr > 25])

Elements > 25: [30 40]


In [15]:
# 10. Broadcasting
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Add 10 to all elements:\n", matrix + 10)
print("Multiply each row by [1, 2, 3]:\n", matrix * np.array([1, 2, 3]))

Add 10 to all elements:
 [[11 12 13]
 [14 15 16]]
Multiply each row by [1, 2, 3]:
 [[ 1  4  9]
 [ 4 10 18]]
